<a href="https://colab.research.google.com/github/Nasar1418/Machine-Learning/blob/main/Colab%20files-2/Matrix_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Creating a Matrix
matrix1=np.asarray([[1,2,3],[4,5,6]])
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [5]:
matrix2=np.random.rand(3,4)
print(matrix2)

[[0.25196275 0.64551408 0.52731286 0.71420153]
 [0.62457581 0.41289243 0.63080497 0.94065452]
 [0.44847562 0.46112999 0.94575004 0.05652119]]


In [7]:
matrix3=np.random.randint(10,50,size=(3,3))
print(matrix3)

[[17 29 24]
 [30 18 28]
 [24 15 31]]


In [9]:
matrix4=np.ones((2,3))
print(matrix4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
matrix5=np.ones((2,3),dtype=int)
print(matrix5)

[[1 1 1]
 [1 1 1]]


In [13]:
matrix6=np.zeros((3,4),dtype=int)
print(matrix6)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
matrix7=np.eye(3,dtype=int)
print(matrix7)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
# Transpose Matrix
matrix8=np.random.randint(1,100,size=(3,4))
print(matrix8)

[[30 28 75 89]
 [63 40  2 27]
 [18 77 46 25]]


In [18]:
transpose=np.transpose(matrix8)
print(transpose)

[[30 63 18]
 [28 40 77]
 [75  2 46]
 [89 27 25]]


In [20]:
# Matrix Addition
a=np.random.randint(1,100,size=(3,4))
b=np.random.randint(1,100,size=(3,4))
print(a)
print(b)

[[15 81 23 63]
 [39 99 34 57]
 [43 67 20 82]]
[[33 17 71 15]
 [19 81 80 15]
 [73 80 42 93]]


In [22]:
sum=a+b
print(sum)

[[ 48  98  94  78]
 [ 58 180 114  72]
 [116 147  62 175]]


In [25]:
# Matrix Subtraction
sub=a-b
print(sub)

[[-18  64 -48  48]
 [ 20  18 -46  42]
 [-30 -13 -22 -11]]


In [41]:
# Matrix Multiplication
a=np.random.randint(1,100,size=(3,4))
b=np.random.randint(1,100,size=(4,3))
print(a)
print(b)

[[47 71 66 77]
 [62 15 24 78]
 [ 2 49 64 58]]
[[18 12 86]
 [40  7 40]
 [28 90  9]
 [32 69 38]]


In [42]:
print(np.dot(a,b))

[[ 7998 12314 10402]
 [ 4884  8391  9112]
 [ 5644 10129  4912]]


In [43]:
# Scalar Multiplication
mul2=5*a
print(mul2)

[[235 355 330 385]
 [310  75 120 390]
 [ 10 245 320 290]]


In [31]:
# Element wise Matrix Manupulation
c=np.random.randint(1,100,size=(3,4))
d=np.random.randint(1,100,size=(3,4))
print(c)
print(d)

[[54 23 15 92]
 [ 2 42 64 78]
 [36 12 47 97]]
[[ 3 79 78  1]
 [67 86 74 96]
 [55 97  1 45]]


In [33]:
print(np.add(c,d))

[[ 57 102  93  93]
 [ 69 128 138 174]
 [ 91 109  48 142]]


In [36]:
print(np.subtract(c,d))

[[ 51 -56 -63  91]
 [-65 -44 -10 -18]
 [-19 -85  46  52]]


In [45]:
print(np.multiply(c,d))

[[ 162 1817 1170   92]
 [ 134 3612 4736 7488]
 [1980 1164   47 4365]]


In [47]:
print(c*d)

[[ 162 1817 1170   92]
 [ 134 3612 4736 7488]
 [1980 1164   47 4365]]
